language: python

# Python versions
python:
  - "2.6"
  - "2.7"
  - "3.3"

# Environments
env:
  - SIXMIN=true
  - SIXMIN=false

# Command to install dependencies
install: 
  - python setup.py install
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' && $SIXMIN == true ]]; then pip uninstall six -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' && $SIXMIN == true ]]; then pip install six==1.1.0; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' && $SIXMIN == false ]]; then pip uninstall six -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' && $SIXMIN == false ]]; then pip install six==1.4.1; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $SIXMIN == true ]]; then pip uninstall six -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $SIXMIN == true ]]; then pip install six==1.1.0; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $SIXMIN == false ]]; then pip uninstall six -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' && $SIXMIN == false ]]; then pip install six==1.4.1; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $SIXMIN == true ]]; then pip uninstall six -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $SIXMIN == true ]]; then pip install six==1.1.0; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $SIXMIN == false ]]; then pip uninstall six -y; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' && $SIXMIN == false ]]; then pip install six==1.4.1; fi

# Command to run tests
script: 
  - python src/transliterate/tests/__init__.py

